name: Test

on:
  [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        scikit-learn-version: ['==1.1.*', '==1.*']
        exclude:
          - python-version: '3.12'
            scikit-learn-version: '==1.1.*'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        env:
          SKLEARN_VERSION: ${{ matrix.scikit-learn-version }}
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.scikit-learn-version }}" == "==1.1.*" ]]; then
            pip install scikit-learn${SKLEARN_VERSION} numpy==1.19.5
          else
            pip install scikit-learn${SKLEARN_VERSION}
          fi
          pip install .[tests]

      - name: Test with pytest
        run: |
          pip install coverage
          coverage run -m pytest tests/

      - name: Codecov
        # You may pin to the exact commit or the version.
        uses: codecov/codecov-action@v4.5.0
